server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mavingue
    username: postgres
    password: 852654
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

app:
  jwt:
    secret: "fjsadahdhasiu23423%&^%FSD4342ASHjfaT*&sayfsafjsa5435"
    expirationSeconds: 7200
