name: Deploy Backend (Render)

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - '.github/workflows/deploy-backend.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'apps/api/**'

jobs:
    build-test:
      name: Build & Test Spring Boot
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: apps/api/app

      steps:
        - 